config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  post 'users/import', as: :import_users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true
  validates :name, :email, presence: true

  def self.import(csv)
    CSV.foreach(csv.path, headers: true, encoding:'iso-8859-1:utf-8') do |row|      
      User.create(name: row['Name'], 
        email: row['Email Address'], 
        phone: row['Telephone Number'],
        website: row['Website'])      
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def import
    if params[:csv]
      if params[:csv].content_type == "text/csv"
        User.import(params[:csv])
        redirect_to root_url, notice: "Users imported."
      else
        redirect_to root_url, notice: "Only csv files allowed."
      end
    else
      redirect_to root_url, notice: "Please select a file."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% if flash.notice %>
  <h3><%= flash[:notice] %></h3>
<% end %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Website</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.phone %></td>
      <td><%= user.website %></td>
    </tr>
  <% end %>
</table>
<h2>Import Users</h2>

<%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :csv %>
  <%= submit_tag "Import" %>
<% end %>